# Generated by Django 4.2.5 on 2023-11-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('artist', models.TextField(max_length=200)),
                ('release_date', models.TextField(max_length=200)),
                ('length', models.IntegerField()),
                ('popularity', models.IntegerField()),
                ('img_url', models.TextField(default='', max_length=200)),
                ('prev_url', models.TextField(max_length=200, null=True)),
                ('danceability', models.FloatField()),
                ('acousticness', models.FloatField()),
                ('energy', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('liveness', models.FloatField()),
                ('loudness', models.FloatField()),
                ('tempo', models.FloatField()),
                ('track_uri', models.TextField(max_length=255)),
                ('yorokobi', models.FloatField(default=0.0)),
                ('kanasimi', models.FloatField(default=0.0)),
                ('kitai', models.FloatField(default=0.0)),
                ('odoroki', models.FloatField(default=0.0)),
                ('ikari', models.FloatField(default=0.0)),
                ('osore', models.FloatField(default=0.0)),
                ('keno', models.FloatField(default=0.0)),
                ('sinrai', models.FloatField(default=0.0)),
                ('lyrics', models.TextField(default='', max_length=2000)),
            ],
        ),
    ]
